_BASE_: "../base_aug_grmix.yaml"

DATASET:
  COCO:
    SET: "val"
DB:
  PATH: "/data/dataset/grmix/orig"
  PARTS: "/data/dataset/grmix/orig/annotations/val_parts.json"
  WHOLES: "/data/dataset/grmix/orig/annotations/val_wholes.json"
AUG:
  TYPE: "test"
  BATCH_SIZE: 6
  PATH: "/home/gregork/workspace/fridge/robot-simulation/data/grmix_test.aug"
